name: Flutter CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows you to trigger the build manually from the GitHub UI

jobs:
  build_android:
    name: Build Android APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.44.2' # Or any stable version you prefer
          channel: 'stable'

      - name: Install Dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload Android Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk

  build_ios:
    name: Build iOS (No Codesign)
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.44.2'
          channel: 'stable'

      - name: Install Dependencies
        run: flutter pub get

      - name: Build iOS
        run: flutter build ipa --no-codesign --release

      - name: Upload iOS Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-build.xcarchive
          path: build/ios/archive/Runner.xcarchive
